AWSTemplateFormatVersion: 2010-09-09
Resources:
  helloworldLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: zhangyu-lambda-test
        S3Key: lambda-triggered-and-read-from-s3-1.0-SNAPSHOT.jar
      FunctionName: zhangyu-lambda-trigered-and-read-from-s3
      Handler: com.ericzhang08.lambdaread.Handler
      Role: arn:aws:iam::494526681395:role/for-aws-training-2
      Runtime: java8
      MemorySize: 512
      Timeout: 30


